In [1]:
import numpy as np

# range and arange same use hota hai

In [8]:
arr = np.array(range(24))
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [15]:
array2 = arr.reshape(2,3,4)
print(array2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
array2.ndim

3

In [20]:
Array3 = np.arange(1,10+1)
print(Array3)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
Array3.reshape(1,10)    # jitne inputs doge utni inputs ya dimesnions bdegi

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [27]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# linearly spaced  generate number from starting index including ending index.

In [30]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Random function

## Random numbers and array from unifrom distribution between 0 and 1

## Uniform distribution means sb numbers ke ane ka chance brabar hota hai 


In [36]:
np.random.rand(1,10)

array([[0.1496452 , 0.76525223, 0.08239026, 0.17422428, 0.60650694,
        0.49674166, 0.87569082, 0.98551013, 0.86020855, 0.57043104]])

In [35]:
np.random.rand(2,5,3)

array([[[0.45451146, 0.68043683, 0.49239368],
        [0.0775018 , 0.04320014, 0.74484816],
        [0.38243827, 0.49289219, 0.47644624],
        [0.48298497, 0.79808877, 0.48776758],
        [0.15619418, 0.29477227, 0.58572379]],

       [[0.3332375 , 0.13972846, 0.02850249],
        [0.13249685, 0.85627915, 0.18017926],
        [0.41348611, 0.90868586, 0.95722206],
        [0.0700244 , 0.95050049, 0.00765038],
        [0.94063631, 0.05793995, 0.90153135]]])

## Random numbers and array from normal distribution between 0 - indicates = randn

### centre ki trf jyada dhyan hoga hai 

In [40]:
np.random.randn(1,5)

array([[-1.17435055,  2.32725722, -0.05034492,  1.88367655,  0.3385507 ]])

# Randint function

In [46]:
array1 = np.random.randint(0,100)
print(array1)

15


In [64]:
array1 = np.random.randint(0,100,(2,5,10))
print(array1)                                 # generating array with dimensions

[[[23 57 67 84 81 90 17 35 48 30]
  [90  6 67 55 61 23  0 37 54 76]
  [15  2 50 72 43 79 51  7 87 50]
  [18 88 32 93 50 86 50 60  6 24]
  [87 41 20 77 50 78  8 78 70 11]]

 [[54 21 19 49 90 22 33 76 98 16]
  [95 34 60 12 19 74 38 12 90 80]
  [86 83 20 10 74  0 95 86 47 40]
  [59 43 84 11 43 85 91 45 37 89]
  [54 76  2 26 93 54 73 29 29 79]]]


In [54]:
# flatten function

In [56]:
#c,k,f,A

In [66]:
array1.flatten("A")

array([23, 57, 67, 84, 81, 90, 17, 35, 48, 30, 90,  6, 67, 55, 61, 23,  0,
       37, 54, 76, 15,  2, 50, 72, 43, 79, 51,  7, 87, 50, 18, 88, 32, 93,
       50, 86, 50, 60,  6, 24, 87, 41, 20, 77, 50, 78,  8, 78, 70, 11, 54,
       21, 19, 49, 90, 22, 33, 76, 98, 16, 95, 34, 60, 12, 19, 74, 38, 12,
       90, 80, 86, 83, 20, 10, 74,  0, 95, 86, 47, 40, 59, 43, 84, 11, 43,
       85, 91, 45, 37, 89, 54, 76,  2, 26, 93, 54, 73, 29, 29, 79],
      dtype=int32)

In [67]:
array1.flatten("c")

array([23, 57, 67, 84, 81, 90, 17, 35, 48, 30, 90,  6, 67, 55, 61, 23,  0,
       37, 54, 76, 15,  2, 50, 72, 43, 79, 51,  7, 87, 50, 18, 88, 32, 93,
       50, 86, 50, 60,  6, 24, 87, 41, 20, 77, 50, 78,  8, 78, 70, 11, 54,
       21, 19, 49, 90, 22, 33, 76, 98, 16, 95, 34, 60, 12, 19, 74, 38, 12,
       90, 80, 86, 83, 20, 10, 74,  0, 95, 86, 47, 40, 59, 43, 84, 11, 43,
       85, 91, 45, 37, 89, 54, 76,  2, 26, 93, 54, 73, 29, 29, 79],
      dtype=int32)

In [69]:
array1.flatten("F")     # block or column  ke sath  chlta hai

array([23, 54, 90, 95, 15, 86, 18, 59, 87, 54, 57, 21,  6, 34,  2, 83, 88,
       43, 41, 76, 67, 19, 67, 60, 50, 20, 32, 84, 20,  2, 84, 49, 55, 12,
       72, 10, 93, 11, 77, 26, 81, 90, 61, 19, 43, 74, 50, 43, 50, 93, 90,
       22, 23, 74, 79,  0, 86, 85, 78, 54, 17, 33,  0, 38, 51, 95, 50, 91,
        8, 73, 35, 76, 37, 12,  7, 86, 60, 45, 78, 29, 48, 98, 54, 90, 87,
       47,  6, 37, 70, 29, 30, 16, 76, 80, 50, 40, 24, 89, 11, 79],
      dtype=int32)

# arrangment of data in rectangular form is known as Matrix

## Rectangular matrix

In [73]:
np.random.randint(0,100,(5,3))   # jisme row jayada column kam

array([[ 6, 98, 76],
       [19, 26, 30],
       [18, 22, 49],
       [42, 63, 80],
       [46, 14, 21]], dtype=int32)

## Square matrix

In [74]:
np.random.randint(0,100,(5,5)) # jisme row or column dono same hogi

array([[29, 99, 54,  3, 90],
       [ 4, 26, 98, 69, 37],
       [ 3,  3, 10, 97, 36],
       [81, 15, 36, 52, 59],
       [23, 33, 82, 55, 88]], dtype=int32)

# Upper matrix - diagonal se uper agr number ho toh wo upper matrix

In [80]:
np.array([
    [1,2,3],
    [0,4,5],
    [0,0,0]
])

array([[1, 2, 3],
       [0, 4, 5],
       [0, 0, 0]])

# Lower Matrix

In [83]:
np.array(
    [
        [0,0,0],
        [1,2,0],
        [3,4,5]
    ]
)

array([[0, 0, 0],
       [1, 2, 0],
       [3, 4, 5]])

# Transpose

In [85]:
array6 = np.random.randint(0,30,(3,3))
print(array6)

[[16 24 18]
 [ 2 18 25]
 [22 17 25]]


In [86]:
array6.transpose()

array([[16,  2, 22],
       [24, 18, 17],
       [18, 25, 25]], dtype=int32)