In [5]:
import numpy as np

# Indexing

In [53]:
np.random.seed(50)    # sbka means sare programs ke same itmes ya same output hogi by seed function or generation process same kaam kregi

In [54]:
arr = np.random.randint(1,20,(3,3))
print(arr)

[[17  1 12]
 [14  2  5]
 [ 7  6  7]]


In [55]:
arr[2][0]           # row and column wise indexing

np.int32(7)

In [56]:
arr[1,2]   # another example of indexing 

np.int32(5)

In [57]:
arr2 = np.random.randint(1,20,(3,5,4))
print(arr2)

[[[14  6  3  8]
  [16  5 15  4]
  [ 7 12 18 11]
  [10  1  7  3]
  [16 10  4  3]]

 [[13  1  4  3]
  [11 17 15  1]
  [ 1 12  8 15]
  [14  8  5  5]
  [ 1 12  1 14]]

 [[14  2 10 12]
  [ 6  1 16  6]
  [ 7  2  5  5]
  [13 15  5 12]
  [ 1  6  9 13]]]


In [58]:
arr2[1]    # indexing block wise

array([[13,  1,  4,  3],
       [11, 17, 15,  1],
       [ 1, 12,  8, 15],
       [14,  8,  5,  5],
       [ 1, 12,  1, 14]], dtype=int32)

In [59]:
arr2[1,4]      # ab usi block ke andr indexing

array([ 1, 12,  1, 14], dtype=int32)

In [60]:
arr2[1,4,2]      # ab usi row mai jo choose ki hai uske andr item selection

np.int32(1)

# Slicing

In [62]:
arr3 = np.random.randint(1,20,(5,5))
print(arr3)

[[ 7 16  1 19 12]
 [ 2 18 15 15  6]
 [ 7 10  5 10  1]
 [16 17 18 17  5]
 [12  2  6 14  4]]


In [65]:
arr3[2:4,1:3]

array([[10,  5],
       [17, 18]], dtype=int32)

In [67]:
arr3[::-1]                #opposite

array([[12,  2,  6, 14,  4],
       [16, 17, 18, 17,  5],
       [ 7, 10,  5, 10,  1],
       [ 2, 18, 15, 15,  6],
       [ 7, 16,  1, 19, 12]], dtype=int32)

In [69]:
arr4 = np.random.randint(1,20,(3,4,4))
print(arr4)

[[[ 8  5 12 14]
  [ 1  9 16  7]
  [ 4  6 12 19]
  [ 2 16  4  4]]

 [[ 1 15 11 13]
  [ 6 13  1 12]
  [15 14 17  2]
  [16 19 12  1]]

 [[ 5 19 14 10]
  [16 18 19 18]
  [ 3  6  2  2]
  [11 19  9 15]]]


In [81]:
arr4[:,1:4,1:2][2:,1]

array([[6]], dtype=int32)

# Assigning value

In [84]:
arr5 = np.random.randint(1,10,(2,5,2))
print(arr5)

[[[9 3]
  [7 6]
  [5 3]
  [4 6]
  [6 3]]

 [[6 8]
  [7 1]
  [1 8]
  [9 8]
  [4 4]]]


In [94]:
arr5[1]

array([[  6,   8],
       [  7,   1],
       [  1,   8],
       [  9,   8],
       [-10,   4]], dtype=int32)

In [90]:
arr5[1,-1,0] = -10

In [91]:
arr5

array([[[  9,   3],
        [  7,   6],
        [  5,   3],
        [  4,   6],
        [  6,   3]],

       [[  6,   8],
        [  7,   1],
        [  1,   8],
        [  9,   8],
        [-10,   4]]], dtype=int32)

In [7]:
arr6 = np.random.randint(1,20,(5,5))
print(arr6)

[[10  5 16  8 13]
 [12  5  8  8  8]
 [ 3 11  2 13 14]
 [17 16  1  9 17]
 [10 19  9 10  9]]


In [8]:
a = arr6[-2:]
print(a)

[[17 16  1  9 17]
 [10 19  9 10  9]]


In [9]:
a = arr6[-2:,-2:]
print(a)

[[ 9 17]
 [10  9]]


# With variable

In [30]:
arr6

array([[ 10,   5,  16,   8,  13],
       [ 12,   5,   8,   8,   8],
       [  3,  11,   2,  13,  14],
       [ 17,  16,   1, 100,  17],
       [ 10,  19,   9,  10,   9]], dtype=int32)

In [31]:
a =arr6[-2:,-2:]
print(a)

[[100  17]
 [ 10   9]]


In [32]:
a[0,0]  = 100

In [33]:
a

array([[100,  17],
       [ 10,   9]], dtype=int32)

In [35]:
arr6

array([[ 10,   5,  16,   8,  13],
       [ 12,   5,   8,   8,   8],
       [  3,  11,   2,  13,  14],
       [ 17,  16,   1, 100,  17],
       [ 10,  19,   9,  10,   9]], dtype=int32)